services:
    wizards_rest.fractal_manager:
        class: League\Fractal\Manager

    wizards_rest.reader:
        class: ''

    wizards_rest.entity_transformer:
        class: WizardsRest\Transformer\EntityTransformer
        arguments:
        - '@wizards_rest.reader'

    wizards_rest.object_manager:
        class: ''

    wizards_rest.paginator:
        class: ''
        arguments:
        - '@router'

    WizardsRest\Serializer:
        arguments:
        - '@wizards_rest.fractal_manager'

    WizardsRest\CollectionManager:
        arguments:
        - '@wizards_rest.paginator'
        - '@wizards_rest.object_manager'

    WizardsRest\Provider:
        arguments:
        - '@wizards_rest.entity_transformer'
        - '@wizards_rest.fractal_manager'

    wizards_rest.format_options_getter:
        class: Wizards\RestBundle\Services\FormatOptions

    wizards_rest.fractal_resource_provider:
        class: Wizards\RestBundle\Services\ResourceProvider
        arguments:
            - '@WizardsRest\Provider'
            - '@wizards_rest.paginator'
            - '@annotation_reader'

    Wizards\RestBundle\Subscriber\SerializationSubscriber:
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - '@WizardsRest\Serializer'
            - '@wizards_rest.fractal_resource_provider'
            - '@wizards_rest.format_options_getter'

    Wizards\RestBundle\Subscriber\ExceptionSubscriber:
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - '@logger'
